### ISSUE TITLE
Worldedit not working

### ISSUE THREAD

**Issue by glassesglasses8** [kaboomserver/server#86]
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: String, Data: [Pair{Type|UUID, 24356362-3834-3662-632d-623436632d34}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[server.jar:3.1.2-SNAPSHOT (git-6496983c-b171)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:3.1.2-SNAPSHOT (git-6496983c-b171)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:3.1.2-SNAPSHOT (git-6496983c-b171)]

**Comment by allinkdev** [comment]
This isn't a WorldEdit issue...

**Comment by allinkdev** [comment]
Please report this to [ViaVersion](https://github.com/ViaVersion/ViaVersion).
